window.SCENT_ID_DATA = {
  navItems: [
    { id: 'home', label: 'Home' },
    { id: 'quiz', label: 'Scent Quiz' },
    { id: 'result', label: 'Your ID' },
    { id: 'detail', label: 'Fragrance' },
    { id: 'moods', label: 'By Mood' },
    { id: 'learn', label: 'Learn' },
    { id: 'lifestyle', label: 'Lifestyle' },
    { id: 'kit', label: 'Discovery Kit' },
    { id: 'sustainability', label: 'Refill' },
    { id: 'profile', label: 'Profile' },
    { id: 'community', label: 'Community' },
  ],
  quizQuestions: [
    {
      id: 'style',
      title: 'What best describes your style?',
      icon: '◇',
      options: ['Fresh', 'Elegant', 'Bold', 'Sensual', 'Creative'],
    },
    {
      id: 'occasion',
      title: 'When do you mostly wear fragrance?',
      icon: '◔',
      options: ['Daily', 'Work', 'Date night', 'Events', 'Relaxing at home'],
    },
    {
      id: 'climate',
      title: 'What climate do you live in?',
      icon: '☼',
      options: ['Hot', 'Cold', 'Mixed', 'Tropical', 'Dry'],
    },
    {
      id: 'energy',
      title: 'What energy do you want your scent to give?',
      icon: '✦',
      options: ['Calm', 'Powerful', 'Romantic', 'Sophisticated', 'Playful'],
    },
    {
      id: 'aesthetic',
      title: 'Which aesthetics do you connect with?',
      icon: '◌',
      options: ['Clean girl', 'Old money', 'Dark academia', 'Soft luxury', 'Main character', 'Minimal chic'],
    },
    {
      id: 'family',
      title: 'Which fragrance families attract you?',
      icon: '✺',
      options: ['Citrus', 'Floral', 'Woody', 'Amber', 'Gourmand', 'Musk', 'Aquatic'],
    },
    {
      id: 'brand',
      title: 'Which brands do you usually like?',
      icon: '▣',
      options: ['Armani', 'Prada', 'YSL', 'Lancôme', 'Maison Margiela', 'Valentino', 'Mugler'],
    },
  ],
  fragrances: [
    {
      id: 'libre',
      name: 'Libre',
      brand: 'YSL',
      type: 'Eau de Parfum',
      family: 'Floral Amber',
      mood: ['Confident', 'Powerful', 'Elegant'],
      style: ['Office', 'Night', 'Signature'],
      top: ['Lavender', 'Mandarin', 'Blackcurrant'],
      heart: ['Orange Blossom', 'Jasmine'],
      base: ['Vanilla', 'Ambergris', 'Cedar'],
      description: 'A tailored floral with Parisian tension—cool lavender illuminated by molten orange blossom and polished amber warmth.',
      image: 'https://images.unsplash.com/photo-1541643600914-78b084683601?auto=format&fit=crop&w=900&q=80',
      score: 96,
      rating: 4.8,
      reviewSnippets: ['Sharp, expensive, unforgettable.', 'My boardroom-to-bar signature scent.'],
      matchReason: 'Its refined floral tension mirrors a profile that wants sophistication with confident presence.',
      lifestyle: {
        movie: 'Call My Agent!',
        music: 'French electro-pop with sleek beats',
        drink: 'Espresso martini',
        destination: 'Golden hour in Paris',
        fashion: 'Tailored power dressing',
      },
      video: 'https://www.youtube.com/embed/5qap5aO4i9A',
    },
    {
      id: 'la-vie-est-belle',
      name: 'La Vie Est Belle',
      brand: 'Lancôme',
      type: 'Eau de Parfum',
      family: 'Floral Gourmand',
      mood: ['Dreamy', 'Cozy', 'Romantic'],
      style: ['Daily', 'Romantic', 'Signature'],
      top: ['Pear', 'Blackcurrant'],
      heart: ['Iris', 'Jasmine', 'Orange Blossom'],
      base: ['Praline', 'Vanilla', 'Patchouli'],
      description: 'A luminous smile in fragrance form—sweet iris and praline softened into a chic, approachable aura.',
      image: 'https://images.unsplash.com/photo-1594035910387-fea47794261f?auto=format&fit=crop&w=900&q=80',
      score: 92,
      rating: 4.7,
      reviewSnippets: ['Soft, comforting, and beautifully feminine.', 'Like dessert and silk at once.'],
      matchReason: 'You lean warm and memorable, and this classic wraps sweetness in polished elegance.',
      lifestyle: {
        movie: 'Amélie',
        music: 'Soft Parisian pop playlist',
        drink: 'Vanilla latte',
        destination: 'Paris sunset café',
        fashion: 'Feminine chic',
      },
      video: 'https://www.youtube.com/embed/jfKfPfyJRdk',
    },
    {
      id: 'my-way',
      name: 'My Way',
      brand: 'Armani',
      type: 'Eau de Parfum',
      family: 'White Floral',
      mood: ['Elegant', 'Dreamy', 'Vacation'],
      style: ['Daily', 'Events', 'Signature'],
      top: ['Bergamot', 'Orange Blossom'],
      heart: ['Tuberose', 'Jasmine'],
      base: ['Cedarwood', 'Vanilla', 'White Musk'],
      description: 'Radiant florals for the collector of moments—softly luminous and globally inspired.',
      image: 'https://images.unsplash.com/photo-1523293182086-7651a899d37f?auto=format&fit=crop&w=900&q=80',
      score: 89,
      rating: 4.6,
      reviewSnippets: ['Bright and polished, never loud.', 'Travel energy in a bottle.'],
      matchReason: 'The profile pairs fresh top notes with sophisticated floral radiance and gentle musk depth.',
      lifestyle: {
        movie: 'Under the Tuscan Sun',
        music: 'Sunlit acoustic lounge',
        drink: 'Sparkling elderflower spritz',
        destination: 'Lake Como terrace',
        fashion: 'Quiet luxury resortwear',
      },
      video: 'https://www.youtube.com/embed/5yx6BWlEVcY',
    },
    {
      id: 'paradoxe',
      name: 'Paradoxe',
      brand: 'Prada',
      type: 'Eau de Parfum',
      family: 'Amber Floral',
      mood: ['Creative', 'Elegant', 'Confident'],
      style: ['Work', 'Daily', 'Night'],
      top: ['Pear', 'Neroli', 'Bergamot'],
      heart: ['Orange Blossom', 'Jasmine Sambac'],
      base: ['Amber', 'White Musk', 'Benzoin'],
      description: 'A modern floral prism—clean, sensual, and sharply styled with Prada precision.',
      image: 'https://images.unsplash.com/photo-1615639164213-aab4d6a2f4d0?auto=format&fit=crop&w=900&q=80',
      score: 94,
      rating: 4.8,
      reviewSnippets: ['Minimalist but addictive.', 'Feels like silk shirting and glow.'],
      matchReason: 'This scent balances modern clarity with soft sensuality, echoing your polished but expressive aesthetic.',
      lifestyle: {
        movie: 'The Devil Wears Prada',
        music: 'Curated city-pop with sleek synths',
        drink: 'White peach bellini',
        destination: 'Milan design week',
        fashion: 'Minimal chic tailoring',
      },
      video: 'https://www.youtube.com/embed/rUxyKA_-grg',
    },
    {
      id: 'lazy-sunday-morning',
      name: 'Lazy Sunday Morning',
      brand: 'Maison Margiela',
      type: 'Eau de Toilette',
      family: 'Clean Floral Musk',
      mood: ['Clean', 'Cozy', 'Calm'],
      style: ['Daily', 'Home', 'Office'],
      top: ['Pear', 'Lily of the Valley', 'Aldehydes'],
      heart: ['Rose', 'Orange Blossom', 'Iris'],
      base: ['White Musk', 'Patchouli', 'Ambrette'],
      description: 'Fresh sheets, sunlight, skin musk—an intimate and airy comfort cloud.',
      image: 'https://images.unsplash.com/photo-1515377905703-c4788e51af15?auto=format&fit=crop&w=900&q=80',
      score: 88,
      rating: 4.5,
      reviewSnippets: ['My clean-girl reset scent.', 'Soft, airy, incredibly easy to wear.'],
      matchReason: 'Your answers suggest graceful minimalism, and this musk-forward freshness feels effortless and lived-in.',
      lifestyle: {
        movie: 'Past Lives',
        music: 'Soft piano and airy indie',
        drink: 'Iced jasmine tea',
        destination: 'Seoul boutique hotel',
        fashion: 'Cashmere basics',
      },
      video: 'https://www.youtube.com/embed/hHW1oY26kxQ',
    },
    {
      id: 'donna-born-in-roma',
      name: 'Donna Born in Roma',
      brand: 'Valentino',
      type: 'Eau de Parfum',
      family: 'Floral Woody',
      mood: ['Seductive', 'Night out', 'Main character'],
      style: ['Night', 'Events', 'Signature'],
      top: ['Blackcurrant', 'Pink Pepper', 'Bergamot'],
      heart: ['Jasmine Grandiflorum', 'Jasmine Tea'],
      base: ['Bourbon Vanilla', 'Cashmeran', 'Guaiac Wood'],
      description: 'Couture glamour with a playful edge—jasmine and vanilla dressed for Rome after dark.',
      image: 'https://images.unsplash.com/photo-1616949755610-8c9bbc08f138?auto=format&fit=crop&w=900&q=80',
      score: 91,
      rating: 4.7,
      reviewSnippets: ['Bold and sparkling all night.', 'This is my after-dark confidence boost.'],
      matchReason: 'It fits a romantic yet commanding profile seeking glamour, warmth, and attention.',
      lifestyle: {
        movie: 'La Dolce Vita',
        music: 'Italian disco glamour',
        drink: 'Blood orange negroni',
        destination: 'Rome rooftop night',
        fashion: 'Studded couture edge',
      },
      video: 'https://www.youtube.com/embed/9bZkp7q19f0',
    },
    {
      id: 'alien',
      name: 'Alien',
      brand: 'Mugler',
      type: 'Eau de Parfum',
      family: 'Amber Woody Floral',
      mood: ['Powerful', 'Seductive', 'Bold'],
      style: ['Night', 'Events', 'Signature'],
      top: ['Jasmine Sambac'],
      heart: ['Cashmeran'],
      base: ['White Amber'],
      description: 'Solar jasmine and mysterious amber in a dramatic aura that lingers like a memory.',
      image: 'https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?auto=format&fit=crop&w=900&q=80',
      score: 90,
      rating: 4.4,
      reviewSnippets: ['Magnetic and unmistakable.', 'One spray and the room remembers you.'],
      matchReason: 'This is for an identity that wants intensity, projection, and presence over softness.',
      lifestyle: {
        movie: 'Dune',
        music: 'Cinematic synth pulse',
        drink: 'Smoked old fashioned',
        destination: 'Desert starlight retreat',
        fashion: 'Architectural eveningwear',
      },
      video: 'https://www.youtube.com/embed/kXYiU_JCYtU',
    },
    {
      id: 'si',
      name: 'Sì',
      brand: 'Armani',
      type: 'Eau de Parfum',
      family: 'Chypre Fruity',
      mood: ['Elegant', 'Romantic', 'Sophisticated'],
      style: ['Work', 'Daily', 'Night'],
      top: ['Blackcurrant Nectar'],
      heart: ['Rose', 'Freesia'],
      base: ['Vanilla', 'Patchouli', 'Woods'],
      description: 'Soft confidence with couture ease—blackcurrant velvet, rose glow, and smooth patchouli.',
      image: 'https://images.unsplash.com/photo-1588405748880-12d1d2a59b08?auto=format&fit=crop&w=900&q=80',
      score: 87,
      rating: 4.6,
      reviewSnippets: ['Subtle elegance that feels grown and glossy.', 'Perfect for date nights and dinners.'],
      matchReason: 'Its graceful fruit-chypre warmth matches users who want presence delivered with softness.',
      lifestyle: {
        movie: 'Atonement',
        music: 'Velvet evening jazz',
        drink: 'Blackcurrant champagne coupe',
        destination: 'Lake district manor escape',
        fashion: 'Old-money romance',
      },
      video: 'https://www.youtube.com/embed/OPf0YbXqDm0',
    },
    {
      id: 'luna-rossa-ocean',
      name: 'Luna Rossa Ocean',
      brand: 'Prada',
      type: 'Eau de Toilette',
      family: 'Aromatic Fougère',
      mood: ['Clean', 'Powerful', 'Vacation'],
      style: ['Daily', 'Office', 'Gym-to-dinner'],
      top: ['Bergamot', 'Pink Pepper', 'Artemisia'],
      heart: ['Lavender', 'Iris', 'Sage'],
      base: ['Vetiver', 'Musk', 'Patchouli'],
      description: 'A fresh marine-leaning fougère with Prada restraint—crisp, smart, and agile.',
      image: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=900&q=80',
      score: 85,
      rating: 4.3,
      reviewSnippets: ['Very easy to wear and well groomed.', 'Fresh but with enough edge to feel modern.'],
      matchReason: 'You respond to polished freshness, and this gives clarity without losing sensual texture.',
      lifestyle: {
        movie: 'The Talented Mr. Ripley',
        music: 'Mediterranean house groove',
        drink: 'Sea salt citrus tonic',
        destination: 'Amalfi yacht afternoon',
        fashion: 'Clean nautical tailoring',
      },
      video: 'https://www.youtube.com/embed/fLexgOxsZu0',
    },
    {
      id: 'myslf',
      name: 'MYSLF',
      brand: 'YSL',
      type: 'Eau de Parfum',
      family: 'Woody Floral',
      mood: ['Clean', 'Confident', 'Creative'],
      style: ['Daily', 'Office', 'Night'],
      top: ['Calabrian Bergamot'],
      heart: ['Orange Blossom'],
      base: ['Patchouli', 'Ambrofix', 'Woods'],
      description: 'A bright modern signature with a fresh opening and smooth woody dry-down designed for self-expression.',
      image: 'https://images.unsplash.com/photo-1496747611176-843222e1e57c?auto=format&fit=crop&w=900&q=80',
      score: 86,
      rating: 4.2,
      reviewSnippets: ['Fresh with personality.', 'Easy to reach for but still distinctive.'],
      matchReason: 'It fits users who want versatility with a little texture and modern edge.',
      lifestyle: {
        movie: 'Her',
        music: 'Neo-soul and minimalist beats',
        drink: 'Grapefruit sparkling soda',
        destination: 'Tokyo creative district',
        fashion: 'Minimal monochrome',
      },
      video: 'https://www.youtube.com/embed/RgKAFK5djSk',
    },
    {
      id: 'by-the-fireplace',
      name: 'By the Fireplace',
      brand: 'Maison Margiela',
      type: 'Eau de Toilette',
      family: 'Woody Gourmand',
      mood: ['Cozy', 'Night out', 'Dreamy'],
      style: ['Night', 'Home', 'Cold weather'],
      top: ['Clove', 'Pink Pepper', 'Orange Blossom'],
      heart: ['Chestnut', 'Guaiac Wood', 'Juniper'],
      base: ['Vanilla', 'Peru Balsam', 'Cashmeran'],
      description: 'Smoked woods, sweet chestnut, and a cashmere finish—the olfactive equivalent of a designer blanket.',
      image: 'https://images.unsplash.com/photo-1512436991641-6745cdb1723f?auto=format&fit=crop&w=900&q=80',
      score: 93,
      rating: 4.9,
      reviewSnippets: ['The ultimate cozy luxury scent.', 'Warm, woody, and unbelievably addictive.'],
      matchReason: 'Your profile embraces warmth and memorable depth, and this fragrance wraps both in texture.',
      lifestyle: {
        movie: 'Little Women',
        music: 'Acoustic fireside session',
        drink: 'Maple old fashioned',
        destination: 'Alpine chalet weekend',
        fashion: 'Chunky knits and suede',
      },
      video: 'https://www.youtube.com/embed/e-ORhEE9VVg',
    },
    {
      id: 'uomo-born-in-roma',
      name: 'Uomo Born in Roma',
      brand: 'Valentino',
      type: 'Eau de Toilette',
      family: 'Woody Vetiver',
      mood: ['Night out', 'Confident', 'Seductive'],
      style: ['Night', 'Events', 'Signature'],
      top: ['Mineral Salt', 'Violet Leaf', 'Ginger'],
      heart: ['Sage', 'Lavandin'],
      base: ['Vetiver', 'Woody Notes'],
      description: 'Mineral freshness cut through with aromatic woods—sharp, modern, and dressed for nightlife.',
      image: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=900&q=80',
      score: 84,
      rating: 4.3,
      reviewSnippets: ['Crisp, sexy, and easy to compliment.', 'Feels like a luxury jacket after dark.'],
      matchReason: 'A fit for profiles asking for charisma, polish, and urban energy.',
      lifestyle: {
        movie: 'Skyfall',
        music: 'Midnight club anthems',
        drink: 'Black cherry soda highball',
        destination: 'Rome midnight piazza',
        fashion: 'Modern rocker tailoring',
      },
      video: 'https://www.youtube.com/embed/hLQl3WQQoQ0',
    },
  ],
  moods: [
    { name: 'Confident', image: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=900&q=80', fragranceIds: ['libre', 'paradoxe', 'myslf'] },
    { name: 'Cozy', image: 'https://images.unsplash.com/photo-1512436991641-6745cdb1723f?auto=format&fit=crop&w=900&q=80', fragranceIds: ['by-the-fireplace', 'la-vie-est-belle', 'lazy-sunday-morning'] },
    { name: 'Seductive', image: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=900&q=80', fragranceIds: ['alien', 'donna-born-in-roma', 'uomo-born-in-roma'] },
    { name: 'Clean', image: 'https://images.unsplash.com/photo-1515377905703-c4788e51af15?auto=format&fit=crop&w=900&q=80', fragranceIds: ['lazy-sunday-morning', 'luna-rossa-ocean', 'myslf'] },
    { name: 'Powerful', image: 'https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&w=900&q=80', fragranceIds: ['libre', 'alien', 'paradoxe'] },
    { name: 'Dreamy', image: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=900&q=80', fragranceIds: ['la-vie-est-belle', 'my-way', 'by-the-fireplace'] },
    { name: 'Creative', image: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=900&q=80', fragranceIds: ['paradoxe', 'myslf', 'lazy-sunday-morning'] },
    { name: 'Elegant', image: 'https://images.unsplash.com/photo-1529139574466-a303027c1d8b?auto=format&fit=crop&w=900&q=80', fragranceIds: ['si', 'my-way', 'libre'] },
    { name: 'Vacation', image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=900&q=80', fragranceIds: ['my-way', 'luna-rossa-ocean', 'lazy-sunday-morning'] },
    { name: 'Night out', image: 'https://images.unsplash.com/photo-1515169067868-5387ec356754?auto=format&fit=crop&w=900&q=80', fragranceIds: ['donna-born-in-roma', 'uomo-born-in-roma', 'alien'] },
  ],
  articles: [
    { title: 'What are fragrance notes?', body: 'Perfume evolves in stages: sparkling top notes, the expressive heart, and the lingering base that becomes your memory trail.' },
    { title: 'Olfactive families explained', body: 'Citrus feels bright, florals feel radiant, woods feel grounded, ambers feel sensual, and gourmands feel deliciously enveloping.' },
    { title: 'Difference between EDT, EDP and extrait', body: 'EDT wears lighter, EDP balances presence and versatility, and extrait offers the richest concentration for a lasting signature.' },
    { title: 'How to choose a signature scent', body: 'Notice what feels like your wardrobe, your energy, and your rituals—not just what smells beautiful on paper.' },
    { title: 'How skin chemistry affects fragrance', body: 'Body heat, hydration, and skin chemistry subtly amplify sweetness, woods, or freshness from the same composition.' },
    { title: 'How to layer fragrances', body: 'Layer one scent for structure and another for texture—think musk with florals, or woods with transparent citrus.' },
    { title: 'How to make your perfume last longer', body: 'Moisturize first, spray pulse points and fabric lightly, and reapply strategically instead of overspraying.' },
  ],
  quickTips: [
    'Spray fragrance on moisturized skin for better longevity.',
    'Test scent in daylight and revisit the dry-down after 30 minutes.',
    'Build a wardrobe: one clean scent, one statement scent, one evening scent.',
    'Store bottles away from steam, heat, and direct light.',
  ],
  whyItems: [
    { title: 'Personalized', text: 'A cinematic scent profile shaped by your taste, mood, and rituals.' },
    { title: 'Educational', text: 'Learn notes, concentration, layering, and skin chemistry with editorial clarity.' },
    { title: 'Sustainable', text: 'Discovery kits and refill pathways support intentional, lower-waste luxury.' },
    { title: 'Emotional', text: 'Connect perfume with music, films, food, fashion, and places you love.' },
    { title: 'Luxury', text: 'Polished design, refined storytelling, and elevated curation throughout.' },
  ],
  videos: [
    { title: 'Perfume Wardrobe Essentials', creator: 'Studio SCENT ID', length: '6:20', cover: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=900&q=80' },
    { title: 'How to Read a Notes Pyramid', creator: 'Fragrance Academy', length: '4:18', cover: 'https://images.unsplash.com/photo-1511988617509-a57c8a288659?auto=format&fit=crop&w=900&q=80' },
    { title: 'Signature Scent Review Roundup', creator: 'Luxury Nose', length: '8:04', cover: 'https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&w=900&q=80' },
  ],
  discoveryKit: {
    title: 'The SCENT ID Discovery Edit',
    image: 'https://images.unsplash.com/photo-1512436991641-6745cdb1723f?auto=format&fit=crop&w=1000&q=80',
    description: 'A curated six-piece wardrobe of modern luxury fragrances chosen to stretch your taste, confirm your favorites, and reveal your next signature.',
    contents: ['Libre', 'Paradoxe', 'My Way', 'Lazy Sunday Morning', 'By the Fireplace', 'La Vie Est Belle'],
    benefits: ['Try before buying', 'Luxury access', 'Less risk', 'More discovery'],
    sustainability: 'Every vial sleeve is recyclable, the keepsake tray is reusable, and your full-size upgrade is refill-eligible where available.',
  },
  reviews: [
    { name: 'Mina T.', scentId: 'Elegant Woody Glow', rating: 5, text: 'SCENT ID actually translated my taste into scents I now wear weekly.' },
    { name: 'Jordan R.', scentId: 'Clean Amber Muse', rating: 4, text: 'The mood and lifestyle matching felt surprisingly accurate and very fun.' },
    { name: 'Ava L.', scentId: 'Velvet Floral Aura', rating: 5, text: 'It feels like a beauty-tech app I would genuinely use.' },
    { name: 'Theo M.', scentId: 'Bold Mineral Night', rating: 4, text: 'Loved the discovery kit logic and the refill storytelling.' },
  ],
  creatorReviews: [
    {
      name: 'Nadia Fleur',
      specialty: 'Perfume Creator',
      quote: 'SCENT ID translates fragrance language into taste language, which makes discovery feel instantly more accessible.',
      image: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=400&q=80',
    },
    {
      name: 'Marco Vale',
      specialty: 'Luxury Reviewer',
      quote: 'The mood and lifestyle pairings create the kind of storytelling that makes perfume feel truly cultural.',
      image: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400&q=80',
    },
    {
      name: 'Elise Moreau',
      specialty: 'Beauty Editor',
      quote: 'It feels presentation-ready: polished enough for a startup pitch, but still intuitive for everyday users.',
      image: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=400&q=80',
    },
    {
      name: 'Jonah Reed',
      specialty: 'Fragrance Educator',
      quote: 'The refill framing is especially smart because it links luxury with long-term ritual instead of one-off buying.',
      image: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=400&q=80',
    },
  ],
  sustainabilityCards: [
    {
      title: 'Refill system',
      copy: 'SCENT ID champions refill-eligible icons and beautifully designed vessels made to live on your vanity longer.',
    },
    {
      title: 'Sustainable luxury',
      copy: 'Premium experiences can still be intentional: refill, reuse, repurchase with care, and reduce unnecessary waste.',
    },
    {
      title: 'Why refill matters',
      copy: 'Refill rituals reward favorites while cutting packaging volume and extending the emotional life of each bottle.',
    },
    {
      title: 'Smart luxury habits',
      copy: 'Start with discovery kits, buy full-size once certain, and set reminders before replacing a signature scent.',
    },
  ],
  refillSteps: [
    'Discover with a curated mini edit before committing to a full bottle.',
    'Choose refill-eligible icons once your signature scent is confirmed.',
    'Set timely reminders so replacement feels intentional rather than impulsive.',
    'Reuse trays, keep caps and bottles, and reduce packaging waste over time.',
  ],
  profile: {
    name: 'Camille Laurent',
    scentId: 'Elegant Woody Glow',
    saved: ['Libre', 'Paradoxe', 'By the Fireplace'],
    watchHistory: ['Perfume Wardrobe Essentials', 'How to Read a Notes Pyramid'],
    favoriteMoods: ['Elegant', 'Cozy', 'Confident'],
    orders: ['The SCENT ID Discovery Edit — Delivered'],
    refillReminders: ['Libre refill reminder in 18 days'],
    recentlyViewed: ['Prada Paradoxe', 'YSL Libre', 'Maison Margiela By the Fireplace'],
    recommendedNext: ['Armani Sì', 'Armani My Way', 'Valentino Donna Born in Roma'],
  },
};
